# Meta
title: LXQt
strapline: The Lightweight Qt Desktop Environment
description: Home of the Debian LXQt team

# Settings
url: '/'
collections:
    downloads:
        output: true
        permalink: /downloads/:path/
    screenshots:
        output: true
        permalink: /screenshots/:path/
defaults:
    -
        scope:
            path: ''
        values:
            unrelimp: null
            relimp: null
            relunimp: null
            unrelunimp:
                - links.html
                - downloads.html
    -
        scope:
            path: ''
            type: downloads
        values:
            unrelunimp:
                - screenshots.html
highlighter: rouge
markdown: kramdown
sass:
    sass_dir: styles
    style: :compressed
permalink: pretty
